### ISSUE TITLE
Consistent named param: Extension Tracker

### ISSUE THREAD

**Issue by Girgias** [php/php-tasks#23]
This is a tracker to see which extensions have been reviewed in regards to #16 

- [x] BCMath (https://github.com/php/php-src/pull/6205)
- [x] BZ2 (https://github.com/php/php-src/pull/6280)
- [x] Calendar (https://github.com/php/php-src/pull/6277)
- [x] COM (https://github.com/php/php-src/pull/6296)
- [x] Ctype (https://github.com/php/php-src/pull/5878)
- [x] cURL (https://github.com/php/php-src/pull/6155)
- [x] Date
- [x] DBA (https://github.com/php/php-src/pull/6292)
- [x] DOM (https://github.com/php/php-src/pull/5893)
- [x] Enchant (https://github.com/php/php-src/pull/6258)
- [x] Exif (https://github.com/php/php-src/pull/6256)
- [x] FFI (https://github.com/php/php-src/pull/6282)
- [x] FileInfo (https://github.com/php/php-src/pull/6206)
- [x] Filter (https://github.com/php/php-src/pull/6229)
- [x] FTP (https://github.com/php/php-src/pull/6254)
- [x] GD (https://github.com/php/php-src/pull/6308)
- [x] GetText (https://github.com/php/php-src/pull/6241)
- [x] GMP (https://github.com/php/php-src/pull/6205)
- [x] Hash (https://github.com/php/php-src/pull/6156)
- [x] Iconv (https://github.com/php/php-src/pull/6234)
- [x] IMAP (https://github.com/php/php-src/pull/6299)
- [x] Intl (https://github.com/php/php-src/pull/6309)
- [x] JSON (https://github.com/php/php-src/pull/6236)
- [x] LDAP (https://github.com/php/php-src/pull/6153)
- [x] libxml
- [x] MBString (https://github.com/php/php-src/pull/6171, https://github.com/php/php-src/pull/6207)
- [x] MySQLi (https://github.com/php/php-src/pull/6172)
- [x] OCI8 (https://github.com/php/php-src/pull/6267)
- [x] ODBC (https://github.com/php/php-src/pull/6303)
- [x] OpCache (https://github.com/php/php-src/pull/6237)
- [x] OpenSSL (https://github.com/php/php-src/pull/6025/, https://github.com/php/php-src/pull/6121)
- [x] PCNTL (https://github.com/php/php-src/pull/6278)
- [x] PCRE (https://github.com/php/php-src/pull/6259)
- [x] PDO (https://github.com/php/php-src/pull/6220, https://github.com/php/php-src/pull/6272)
- [x] PDO_SQLite (https://github.com/php/php-src/pull/6310)
- [x] PDO_PGSql (https://github.com/php/php-src/pull/6329)
- [x] PGSQL (https://github.com/php/php-src/pull/6294, https://github.com/php/php-src/pull/6304)
- [x] Phar (https://github.com/php/php-src/pull/6307)
- [x] POSIX (https://github.com/php/php-src/pull/6275)
- [x] PSpell (https://github.com/php/php-src/pull/6257)
- [x] Readline (https://github.com/php/php-src/pull/6240)
- [x] Reflection (https://github.com/php/php-src/pull/5850, https://github.com/php/php-src/pull/6230)
- [x] Session (https://github.com/php/php-src/pull/6239)
- [x] SHMOP (https://github.com/php/php-src/pull/6238)
- [x] SimpleXML (https://github.com/php/php-src/pull/5893)
- [x] SNMP (https://github.com/php/php-src/pull/6298)
- [x] SOAP (https://github.com/php/php-src/pull/6300)
- [x] Sockets (https://github.com/php/php-src/pull/6276)
- [x] Sodium (https://github.com/php/php-src/pull/6279)
- [x] SPL (https://github.com/php/php-src/pull/6284)
- [x] SQLite3 (https://github.com/php/php-src/pull/6264)
- [x] Standard (https://github.com/php/php-src/pull/6046, https://github.com/php/php-src/pull/6214)
- [x] SysVMsg (https://github.com/php/php-src/pull/6247)
- [x] SysVSem (https://github.com/php/php-src/pull/6248)
- [x] SysVShm (https://github.com/php/php-src/pull/6249)
- [x] Tidy (https://github.com/php/php-src/pull/6283)
- [x] Tokenizer (https://github.com/php/php-src/pull/6232)
- [x] XML (https://github.com/php/php-src/pull/6297)
- [x] XMLReader (https://github.com/php/php-src/pull/6255)
- [x] XMLWriter (https://github.com/php/php-src/pull/6202)
- [x] XSL (https://github.com/php/php-src/pull/6295)
- [x] ZIP (https://github.com/php/php-src/commit/dafc72cb33ea677cd0b3caffc8fe7bf510a4bf7c)
- [x] ZLIB (https://github.com/php/php-src/pull/6250)
- [x] Zend/ (https://github.com/php/php-src/pull/5847, https://github.com/php/php-src/pull/6228)

Unresolved questions:

- [ ] https://github.com/php/php-src/pull/6214#issuecomment-700706560 and following

**Comment by remicollet** [comment]
Checked zip, consistency fixed in https://github.com/php/php-src/commit/dafc72cb33ea677cd0b3caffc8fe7bf510a4bf7c

**Comment by remicollet** [comment]
As a side note, this also means php documentation probably needs a big update, so the parameters name describe there matches actual one in 8

Done for **zip** in https://github.com/php/doc-en/commit/462e36980658cbed6b76f188038edc796ae379bc and https://github.com/php/doc-en/commit/002b7dd50a0cb86e965022610f08f240cadb6fcc

**Comment by kocsismate** [comment]
@remicollet Yes, we have already started working on (at least making it possible to) automatically generate function signatures for the manual.

And later we should change the parameter names in the descriptions as well.

**Comment by cmb69** [comment]
> And later we should change the parameter names in the descriptions as well.

That should be done as soon as the signatures are changed in the manual. :)

**Comment by kocsismate** [comment]
> That should be done as soon as the signatures are changed in the manual. :)

True :) I messed up the timeline ^^ Should have said "afterwards" or "right after"

**Comment by dtakken** [comment]
PR for mysqli is here: https://github.com/php/php-src/pull/6172

@Girgias Could you please add it to the list?

**Comment by dtakken** [comment]
Related PR to update the coding standards to include parameter names:

php/php-src/pull/5897

**Comment by Crell** [comment]
PR for pgsql: https://github.com/php/php-src/pull/6304

Waiting to see if it passes tests... :sweat_smile:

**Comment by nikic** [comment]
I believe we're done here.
