### ISSUE TITLE
PHP 8 documentation tracker

### ISSUE THREAD

**Issue by Girgias** [php/php-tasks#26]
Pages which need to be added/modified for complete documentation of PHP 8:

Based of the migration guide: https://github.com/php/doc-en/pull/170

(Currently W.I.P.)

## Core:

- [ ] New features:
   - [x] Type declarations (https://github.com/php/doc-en/pull/174)
     - [x] Union types 
     - [x] mixed
     - [x] static return
  - [x] Constructor Promotion (https://github.com/php/doc-en/pull/188)
  - [x] match expressions (https://github.com/php/doc-en/pull/206)
     - [x] UnhandledMatchError
  - [ ] named params
  - [ ] Attributes
  - [ ] Null-safe operator
  - [ ] Stringable interface
  - [ ] WeakMap (core)
  - [ ] $object::class
  - [ ] Catch without variable
  - [ ] traits can now have abstract methods
  - [x] ValueError (https://github.com/php/doc-en/pull/205)
- [ ] Modified features:
  - [ ] throw expression
  - [ ]  &new; and &instanceof; can now be used with arbitrary expressions
  - [ ] trailling commas in parameter lists
  - [ ] private methods do not enforce inheritance rules on child classes any more (except __construct)
  - [ ] Numeric strings
    - [ ] Comparison
    - [ ] When a string is considered numeric 
  - [ ] Operator precedence
    - [ ] Concatenation
- [ ] Deprecated
   - [ ] Optional args after mandatory ones

## Functions:
- [ ] New functions
  - [ ] get_resource_id()
  - [ ] `str_contains()`
  - [ ] `str_start_with()`
  - [ ] `str_ends_with()`
- [ ] Modified functions
  - [ ] `printf` and friends
- [ ] Deprecated
  - [ ] PGSQL aliases

**Comment by TysonAndre** [comment]
>  traits can now have abstract methods

That should say "abstract trait methods are validated against the implementation provided in the using class, according to our usual inheritance rules." and "traits can now have abstract **private** methods"

https://wiki.php.net/rfc/abstract_trait_method_validation

>  named params

named arguments - "Named arguments allow passing arguments to a function based on the parameter name, rather than the parameter position."

The php 8 migration docs in the linked pr seem to be correct

**Comment by Girgias** [comment]
> 
> 
> > traits can now have abstract methods
> 
> That should say "abstract trait methods are validated against the implementation provided in the using class, according to our usual inheritance rules." and "traits can now have abstract **private** methods"
> 
> https://wiki.php.net/rfc/abstract_trait_method_validation
> 
> > named params
> 
> named arguments - "Named arguments allow passing arguments to a function based on the parameter name, rather than the parameter position."
> 
> The php 8 migration docs in the linked pr seem to be correct

This rather a tracker and not an accurate description of the features, but will modify them

**Comment by emmanix2002** [comment]
@Girgias I'd like to help with adding the docs for a few of the new strig functions

**Comment by Girgias** [comment]
> 
> 
> @Girgias I'd like to help with adding the docs for a few of the new strig functions

The best way to do that is to fork https://github.com/php/doc-en/ and then to base the documentation on the `strpos()` function which is located here: blob/master/reference/strings/functions/stripos.xml

**Comment by matthewtrask** [comment]
I'll take a shot at the `$object::class` docs.

**Comment by jrfnl** [comment]
To add to the update list:
- [ ] Update the function signatures of all functions and methods where parameters have been renamed in anticipation of named parameters. (as otherwise people won't know what parameter names to use for PHP native functions)
- [ ] Where relevant, update the function signatures of all functions and methods where type declarations have been added or have been changed.
    In the case of _changed_: including adding a changelog entry to the function page.

**Comment by Girgias** [comment]
> 
> 
> To add to the update list:
> 
>     * [ ]  Update the function signatures of all functions and methods where parameters have been renamed in anticipation of named parameters. (as otherwise people won't know what parameter names to use for PHP native functions)
> 
>     * [ ]  Where relevant, update the function signatures of all functions and methods where type declarations have been added or have been changed.
>       In the case of _changed_: including adding a changelog entry to the function page.

This is already handled "internally" by us as @kocsismate is running a script to update the docs based on the official stubs and I'm confident he's tracking which extensions have already been covered.

My intent with this issue tracker is to track changes which don't need to be done in bulk, as those would be rather painful to do manually.

So I can add them, but I'm not sure it makes a lot of sense as I don't want someone to attempt to do this specific part.

**Comment by jrfnl** [comment]
@Girgias Happy to hear this will be handled via a script and totally understand not adding it to the list in that case. Kudos to @kocsismate.

Just figured I'd mention it as I already ran into this - case in point: the example code in the Named Arguments RFC for `array_fill()` will no longer work as `$num` has been renamed to `$count` ;-)

**Comment by kocsismate** [comment]
And thanks to cmb, there is already a tracker for the function signature updates in the manual: https://github.com/php/doc-en/labels/methodsynopses

**Comment by emmanix2002** [comment]
> > @Girgias I'd like to help with adding the docs for a few of the new strig functions
> 
> The best way to do that is to fork https://github.com/php/doc-en/ and then to base the documentation on the `strpos()` function which is located here: https://github.com/php/doc-en/blob/master/reference/strings/functions/stripos.xml

Thanks

**Comment by emmanix2002** [comment]
@Girgias opened PR for `str_contains` here: https://github.com/php/doc-en/pull/216

**Comment by 50bhan** [comment]
Is there any guidelines about how to write proper docs for PHP?

**Comment by emmanix2002** [comment]
@50bhan I simply followed the instructions in the repo's README to understand set up and you can look at the review comments on my first PR to understand some of the things to watch out for.

https://github.com/php/doc-en/pull/216

**Comment by cmb69** [comment]
There is a small [tutorial for doc contributors](http://doc.php.net/tutorial/). [PRs to improve that tutorial](https://github.com/php/web-doc/pulls) are also welcome!

**Comment by emmanix2002** [comment]
Any suggestions for the preferred directory for the `get_resource_id()` and `get_debug_type()` documentation reference?

**Comment by emmanix2002** [comment]
> Any suggestions for the preferred directory for the `get_resource_id()` and `get_debug_type()` documentation reference?

No worries, I've found the right directory. I'll add them to the `var/functions` directory 😬

**Comment by flow-control** [comment]
@Girgias I checked the `ZipArchive::setProgressCallback()` and `::setCancleCallback()` and found out, that these two methods are in fact named `::registerProgressCallback()` and `::registerCancleCallback()`. Their documentation exists already [here](https://www.php.net/manual/en/ziparchive.registercancelcallback.php) and [there](https://www.php.net/manual/en/ziparchive.registerprogresscallback.php).
So I created this PR https://github.com/php/doc-en/pull/228

**Comment by Crell** [comment]
Trailing commas PR: https://github.com/php/doc-en/pull/241

**Comment by cjbj** [comment]
@Girgias For the OCI8 renamed classes (OCI-Lob to OCILob & OCI-Collection to OCICollection) task the new PR is https://github.com/php/doc-en/pull/246, replacing #237.  With thanks to @cmb69.

**Comment by ekinhbayar** [comment]
If nobody has started on it yet, I'd like to help with documenting named arguments over the weekend. I think [function arguments](https://www.php.net/manual/en/functions.arguments.php) page would be a good candidate for this. Thoughts? cc @Girgias @cmb69

**Comment by Girgias** [comment]
> 
> 
> If nobody has started on it yet, I'd like to help with documenting named arguments over the weekend. I think [function arguments](https://www.php.net/manual/en/functions.arguments.php) page would be a good candidate for this. Thoughts? cc @Girgias @cmb69

This would be the correct page, I wonder if at the same time you could do a paragraph about how Optional args after mandatory ones are deprecated as of PHP 8.0.0.

**Comment by ekinhbayar** [comment]
@Girgias oh good one, will do! Thanks.

**Comment by ekinhbayar** [comment]
Here's the PR for named arguments and deprecation of optional args after mandatory ones: https://github.com/php/doc-en/pull/251

**Comment by bkdotcom** [comment]
`ReflectionParameter::getType()` is NOT deprecated!

`ReflectionParameter::getClass()`, `ReflectionParameter::isArray()`, and `ReflectionParameter::isCallable()` have been deprecated with the preferred method being `getType()`

**Comment by Girgias** [comment]
Indeed fixed that
